# version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: hasabir
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    # volumes:
    #   - ../subject:/tmp/data


  adminer:
    image: adminer
    restart: always
    # networks:
    #   - mynetwork
    depends_on:
      - db
    ports:
      - 8080:8080


  # pgAdmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin_container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   depends_on:
  #     - db
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - ".:/var/lib/pgadmin"

volumes:
  postgres_data:
  # pgAdmin_data:

  # dbeaver:
  #   image: dbeaver/cloudbeaver:latest 
  #   container_name: dbeaver_container
  #   ports:
  #     - "5051:8978"
  #   depends_on:
  #     - db