version: 3.8

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscines
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data