
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: hasabir
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - ./data:/tmp/data
      - /home/hasabir/psql:/var/lib/postgresql/data


  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - /home/hasabir/pgAdmin:/var/lib/pgadmin




# sudo chown -R 5050:0 /home/hasabir/pgAdmin
# sudo chmod -R 775 /home/hasabir/pgAdmin
