version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: hasabir
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
